# Generated by Django 4.2.3 on 2024-04-08 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('x', models.CharField(max_length=50)),
                ('y', models.CharField(max_length=50)),
                ('history', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='TagModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PlaceANDTag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PlaceApp.placemodel')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PlaceApp.tagmodel')),
            ],
        ),
    ]
