# Generated by Django 4.2.3 on 2024-04-08 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PlaceApp', '0002_favoriteplace'),
        ('CommentApp', '0002_commentmodel_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentmodel',
            name='place',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='PlaceApp.placemodel'),
            preserve_default=False,
        ),
    ]
